export const USER_CONST = {
    STUDENT_ID_MAX_LENGTH: 32,
    NAME_MAX_LENGTH: 256,
    PERSONAL_ID_MAX_LENGTH: 20,
    PHONE_NUMBER_MAX_LENGTH: 20,
    USERNAME_MIN_LENGTH: 4,
    USERNAME_MAX_LENGTH: 64,
    PASSWORD_MIN_LENGTH: 4,
    PASSWORD_MAX_LENGTH: 128,
    EMAIL_MAX_LENGTH: 512,
    ADDRESS_MAX_LENGTH: 512,
    TOKEN_MAX_LENGTH: 256,
};
